version: '3'

services:
  intercept-dns:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARCH: amd64
    restart: on-failure
    environment:
      REMOTE_DNS: 1.1.1.1
      REMOTE_PORT: 53
    ports:
      - '53:53'